language: python
python:
- 3.7
install:
- python setup.py install
- pip install -r tests/test-requirements.txt
script:
- pytest tests/tests.py
deploy:
  provider: pypi
  user: dhaitz
  password:
    secure: IUHrHz2uzxdWns9+q5OE36bgmwTrVrthExpmgZfUsqFlG+Tm+1w5eWIUOm8GQc7pI0OdcyN2dISL5Fyh3gnXnsRKyBm3YWv4ucizfmqH4SsKLtizFmG5Eeq/s+aXB5RsJmWJ9Qt1YsFHPRo80RjWUauIvUupzqpS314IAcLu3v3YJKH8L+xWFNE552KHcPSJJy00cpXLkwuKFQnwIfutzpOctA3Lb1frVq3U25dTsynJ3ScBz3AkQm5BTYxD6H/POinf+Cdm5plhFCm4fZ3QxICylnF1AjZo8w9KPdC6THlsHsX+3ZJu6JW2caaM/fWFgc3ZTUm+MORX14UMxRnvB24Ae1FmpeaOxWoYfDDv8Ws3633WucY5+kBOECGYqql43pRP1QrqqDLf8qjiwyWMjovt+4RKWJlzTLG5iMOLSy/s2BBeHVC82DdmXRXKzbsnHPKrxdlGvhj16v7Hwgrcjuvp51RhErJYyFWkK2DGC3lQ1jkFxbk9+2yfDm11eyNQKa84o8F0BzN9DYiL64EHaDES7ChLZ05dI8VWUrETYU0M7W+qo2P9iwBv/Rmfr97ILs28kQ9N4rc5OxyG+Lh91UTSyz5GSW2NHBMXDuIVX22w7bcfWTjoDqObyqnbU5YTm4Oh9iSUgW0X8qSROdZx+uhcadn3IQ/Rfphh413wBVY=
  distributions: bdist_wheel
  on:
    tags: true
