language: python
python:
- 3.7
install:
- python setup.py install
- pip install -r tests/test-requirements.txt
script:
- pytest tests/tests.py
deploy:
  provider: pypi
  user: dhaitz
  password:
    secure: LTCb4FbQpUKL/fKYE62J9CjfXfZjQI8heEtvCd+brHjqevqnUcblvldnhFEefPzOXFwnXPbXaNYPVl7Fo8qzBK1ed7SH94vCL62Q8RTBpixo/p9d0zR3/LuNztsh4EI5hDPscr+SCItuTfwUwwBYerYkCz7KEjqfvr04CzDYzLj0jRgY4olGSepUYM3AjjDl6Tkx5QN9iG24ZtADhz99itvRkufpVamIgE/JrBEcAN6Msop/r5DFDp4BkiXZCxpIFo1pizsuMyxO3IEU6GaicDzfpDu0byZyziXq0s0YI1Hn0B2dx9SHIxRsJPwwf2VVn6B9W8O8/FmSCgHD1ZcMQkM+xEF5D8QA5gkqPld8dMlHh24HFPbt3zmd8OucEJuanE5ksPSJRpEzewnKxRxvi/xywmkdEtD2qF5Hlwi4Wx7XQSAR99qT1Vf2pwpW0tPzzDvwf1YpZl9J1t53VAJpEp71mSLogn1Y3QrjJ0o28v1L9uQBZMkbZNZTSZgyx2VIAd15R482Y8E02buZ8Yu+u9fLeK0TLCCwX8EFcVWo1Dg71AlTrCRSJfHwB9fsFmPlZtZ0fgAZ0tGYB8uY/1nApY8/XOni2e4VHNkE/jOdxDlxjlGDTMAL/ISgxpHtlDmuznbHRAoPBu5Ue51nPPL8Nc405PSak/oUfKq8uq404hA=
  distributions: bdist_wheel
  on:
    tags: true
