language: python
python:
- 3.7
install:
- python setup.py install
- pip install -r tests/test-requirements.txt
script:
- pytest tests/tests.py
deploy:
  provider: pypi
  user: dhaitz
  password:
    secure: DCpDPgtncRlPM7MwWx+LEa9ivhKvZqePApWOspXwaooY5+QpcpAIe+mhIbj03IJJsLLGreMUw9O4XxxrmDHhoncz7TnPNqJwTnTW1G3d2O4Bt9mKVh3i1khjNEUCAeoFB+wJqFYHRMCzmRXnrbAP8aR9+4WI3L8OF49IcLO9vpqOyJ5vbM9EMidpju7zxcx1ZrWfukTO4rWR+rvCml/dgSWgL5xP+xc9Qm3z9iPlgujC+U/OMlTj0NczJm7h4bIXiOEZVjhGC+1K8bNkIcx3p//jOLqkfe5TCOrYy2TyXCgXgimn9HJlTzcWlqRmlL4fDShy1x6axL6ffgDS2kuV6TUR6QRSbW0zsxpCKnDDbWVMKHQ+DmbiIAkduP6j6/HhPWbnYfQcp54Z3kbSj8XPD4WmiaXfUPTVp7GaMTLv/+4CuEM6gUhqS9WqJ4uEtORyF6yJ2xWjHiAQZ7u+amMgTyqXDdEc0G7jj2YKN7mmACkKoBgjocPPmsru3W+t125YxipEjKYlOMyZ/IQ7AH2edtpjqPtyrBzprgpXTJkc0f5kmH+8fwR3LhneUcD53dM4NXzCq6K2iI3swoW/xU95zXYb7wFZphm+Kd5a9p6pYTm6NE3HSPHMeHi+dtdgi43RgerVuLl1Zz4WuzzLN3s7/bojGyKAl0MUTWlZFlYUyRM=
  distributions: bdist_wheel
  on:
    tags: true
